alloy:
  clustering:
    enabled: true

  configMap:
    create: true
    content: |
      // CLUSTER DISCOVERY
      discovery.kubernetes "nodes" {
        role = "node"
      }

      discovery.kubernetes "apiserver" {
        role = "endpoints"
      }

      discovery.kubernetes "ksm" {
        role = "endpoints"
      }

      discovery.relabel "api_filter" {
        targets = discovery.kubernetes.apiserver.targets
        rule {
          source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_service_name", "__meta_kubernetes_endpoint_port_name"]
          action = "keep"
          regex = "default;kubernetes;https"
        }
      }

      discovery.relabel "ksm_filter" {
        targets = discovery.kubernetes.ksm.targets
        rule {
          source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_service_name", "__meta_kubernetes_endpoint_port_name"]
          action = "keep"
          regex = "monitoring;kube-state-metrics;http"
        }
      }

      // SCRAPING
      //// HOST & POD METRICS
      prometheus.scrape "kubelet" {
        targets = discovery.kubernetes.nodes.targets
        scheme  = "https"
        scrape_interval = "10s"
        tls_config {
          ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          insecure_skip_verify = true
        }
        bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
        forward_to = [prometheus.remote_write.external_server.receiver]
      }

      prometheus.scrape "kube_state_metrics" {
        targets    = discovery.relabel.ksm_filter.output
        scrape_interval = "10s"
        forward_to = [prometheus.remote_write.external_server.receiver]
      }

      //// CONTAINER METRICS
      prometheus.scrape "cadvisor" {
        targets    = discovery.kubernetes.nodes.targets
        scheme     = "https"
        metrics_path = "/metrics/cadvisor"
        scrape_interval = "10s"
        tls_config {
          ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          insecure_skip_verify = true
        }
        bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
        forward_to = [prometheus.remote_write.external_server.receiver]
      }

      //// API
      prometheus.scrape "apiserver" {
        targets    = discovery.relabel.api_filter.output
        scheme     = "https"
        scrape_interval = "10s"
        tls_config {
          ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          insecure_skip_verify = true
        }
        bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
        forward_to = [prometheus.remote_write.external_server.receiver]
      }

      // Push
      prometheus.remote_write "external_server" {
        endpoint {
          url = "http://<MON_SRV_IP>/prometheus/api/v1/write"
        }
      }

rbac:
  create: true

controller:
  type: 'daemonset'

service:
  enabled: true