{
 "title": "cluster_galera",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "flow_paused",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_flow_control_paused",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "etat_cluster",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_cluster_size",
     "legendFormat": "__auto"
    },
    {
     "expr": "min(mysql_global_status_wsrep_cluster_status)",
     "legendFormat": "-"
    }
   ]
  },
  {
   "title": "Receive Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_local_recv_queue",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "received_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_received_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}