services:
  mimir:
    image: grafana/mimir:2.10.1
    container_name: mimir
    user: "root"
    restart: unless-stopped
    command: ["-config.file=/etc/mimir.yml"]
    volumes:
      - ./configs/mimir.yml:/etc/mimir.yml:ro
      - mimir_data:/tmp/mimir

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mimir

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --web.external-url=http://localhost/prometheus/
      - --web.route-prefix=/
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_DOMAIN=stage.etl.cld.education
      - GF_SERVER_ROOT_URL=https://stage.etl.cld.education/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      # Autorise le domaine pour le mécanisme CSRF
      - GF_SECURITY_CSRF_ADDITIONAL_ORIGINS=https://stage.etl.cld.education
      # Autorise toutes les sources pour le mécanisme d'origine (Joker *)
      - GF_SECURITY_CSRF_TRUSTED_ORIGINS=*
      # Requis pour le bon fonctionnement des cookies en HTTPS
      - GF_SESSION_COOKIE_SECURE=true
      - GF_SESSION_COOKIE_SAMESITE=none
    depends_on:
      - prometheus

volumes:
  mimir_data:
